name: Feature Request
description: Suggest a new feature or enhancement for the WhoRang AI Doorbell Integration
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - Beast12

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all applicable items before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the [documentation](https://github.com/Beast12/whorang-integration/blob/main/README.md) to ensure this feature doesn't already exist
          required: true
        - label: This feature request is specific to the Home Assistant integration (not the backend service)
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: "Add support for..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: "I'm frustrated when... It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternatively, we could..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - "New Entity Type"
        - "New Service"
        - "Configuration Enhancement"
        - "AI Provider Support"
        - "Automation/Event Enhancement"
        - "Dashboard/UI Enhancement"
        - "Performance Improvement"
        - "Security Enhancement"
        - "Documentation Improvement"
        - "Developer Experience"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my use case"
        - "Critical - Blocking my usage"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Detailed Use Case
      description: |
        Provide a detailed description of how you would use this feature:
        - What would you do with it?
        - How would it fit into your automation setup?
        - What would the user experience look like?
      placeholder: |
        Example scenario:
        1. User configures...
        2. When X happens...
        3. The system would...
        4. User receives...

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Considerations
      description: |
        If you have technical knowledge, please share any implementation ideas:
        - Suggested entity types or attributes
        - Service parameters
        - Configuration options
        - Integration with existing features
      placeholder: |
        Example:
        - New sensor: sensor.whorang_feature_name
        - Service: whorang.new_service with parameters...
        - Configuration option in integration options

  - type: textarea
    id: examples
    attributes:
      label: Examples and References
      description: |
        Provide examples or references that might help:
        - Similar features in other integrations
        - Code examples or mockups
        - Screenshots or diagrams
        - Links to relevant documentation

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to contribute code (if I have the skills)
        - label: I would be willing to provide feedback during development

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or information about the feature request:
        - Related issues or discussions
        - Impact on existing functionality
        - Compatibility considerations
        - Timeline preferences

  - type: checkboxes
    id: understanding
    attributes:
      label: Understanding
      options:
        - label: I understand this is a feature request and not a bug report
          required: true
        - label: I understand that feature implementation depends on maintainer availability and priorities
          required: true
        - label: I understand that complex features may take time to implement
          required: true
